#!/bin/sh
# configure — bundled with the stable-haskell multi-target GHC bindist.
#
# Multi-target bindist combines: native ghc, wasm32-unknown-wasi-ghc,
# javascript-unknown-ghcjs-ghc. All three are the same physical binary
# (stage2 native ghc), dispatched at runtime via argv[0]:
#   ghc                          -> uses lib/settings + lib/$HOST_PLATFORM
#   wasm32-unknown-wasi-ghc      -> uses lib/targets/wasm32-unknown-wasi/lib/settings
#   javascript-unknown-ghcjs-ghc -> uses lib/targets/javascript-unknown-ghcjs/lib/settings
#
# Minimal autoconf-style stub so that ghcup's standard
# "./configure --prefix=DIR && make install" install path works.

set -e

prefix=
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix=*) prefix="${1#--prefix=}" ;;
    --prefix)   shift; prefix="$1" ;;
    *) ;;     # accept and ignore other autoconf args
  esac
  shift
done

if [ -z "$prefix" ]; then
  echo "error: --prefix=DIR is required" >&2
  exit 1
fi

cat > config.mk <<EOF
# generated by configure $(date '+%Y-%m-%dT%H:%M:%SZ')
prefix = $prefix
EOF

echo "configured stable-haskell multi-target GHC bindist with prefix=$prefix"
