#!/bin/sh
# configure — bundled with the stable-haskell wasm32-unknown-wasi GHC bindist.
#
# Minimal autoconf-style stub so that `ghcup install ghc <version>`'s
# standard "./configure --prefix=DIR && make install" flow works.
#
# All we do is record the install prefix; the real work happens in the
# bindist's Makefile install target (which just copies bin/ + lib/ into
# the prefix and refreshes the package-db cache).

set -e

prefix=
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix=*)
      prefix="${1#--prefix=}"
      ;;
    --prefix)
      shift
      prefix="$1"
      ;;
    # accept and ignore other autoconf args ghcup or users may pass
    *)
      ;;
  esac
  shift
done

if [ -z "$prefix" ]; then
  echo "error: --prefix=DIR is required" >&2
  exit 1
fi

cat > config.mk <<EOF
# generated by configure $(date '+%Y-%m-%dT%H:%M:%SZ')
prefix = $prefix
EOF

echo "configured wasm32-unknown-wasi GHC bindist with prefix=$prefix"
