-- | The Cmm files that GHC generates and compiles when it links the RTS
-- into a program: the generic apply code and the register-saving frames of
-- rts/Jumps.h.  See Note [Link-time RTS Cmm files] here and
-- Note [Linking the generic apply code] in GHC.Driver.Pipeline, which
-- compiles them ('GHC.Driver.Pipeline.mkRtsCmmObjs').
module GHC.Linker.RtsCmm
  ( GenFile(..)
  , genFiles
  , genFileVecWidth
  , genFile
  , genJumps
  ) where

import GHC.Prelude

import GHC.Platform
import GHC.StgToCmm.AutoApply ( genAutoApply )

{- Note [Link-time RTS Cmm files]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Two families of RTS routines exist once per argument-register width (scalar,
V16, V32, V64) and need the matching -mavx flags on x86:

  * the generic apply code, generated by 'genAutoApply' (AutoApply*.cmm), and

  * the register-saving frames stg_stack_underflow_frame_* and
    stg_restore_cccs_* (rts/Jumps.h, see Note [realArgRegsCover] in
    GHC.Cmm.CallConv), whose four variants are two-line wrappers that set
    ARG_REGS_V* and include Jumps.h.

Both encode the target's argument registers, which the compiler already
knows, and both would need per-file compiler flags in the RTS build.  So GHC
generates and compiles all of them when it links the RTS into something; see
Note [Linking the generic apply code] in GHC.Driver.Pipeline, whose
mkRtsCmmObjs does the work.  'genFiles' lists them, 'genFile' produces each
one's source, and 'genFileVecWidth' says which vector width (and hence which
-mavx flag) a file needs.  Jumps.h itself stays in the RTS as an installed
header.
-}

-- | A Cmm file that GHC generates and links along with the RTS.
-- See Note [Link-time RTS Cmm files].
data GenFile
  = GenAutoApply (Maybe Int)  -- ^ the generic apply code, for the given vector width
  | GenJumps     (Maybe Int)  -- ^ wrapper around rts/Jumps.h for the given vector width

-- | All the files, with the names they are conventionally given.
genFiles :: [(FilePath, GenFile)]
genFiles =
  [ ("AutoApply.cmm",     GenAutoApply Nothing)
  , ("AutoApply_V16.cmm", GenAutoApply (Just 16))
  , ("AutoApply_V32.cmm", GenAutoApply (Just 32))
  , ("AutoApply_V64.cmm", GenAutoApply (Just 64))
  , ("Jumps_D.cmm",       GenJumps Nothing)
  , ("Jumps_V16.cmm",     GenJumps (Just 16))
  , ("Jumps_V32.cmm",     GenJumps (Just 32))
  , ("Jumps_V64.cmm",     GenJumps (Just 64))
  ]

-- | The vector width a file is specialised to, if any.
genFileVecWidth :: GenFile -> Maybe Int
genFileVecWidth (GenAutoApply v) = v
genFileVecWidth (GenJumps v)     = v

-- | The source of one of the files.
genFile :: Platform -> GenFile -> String
genFile platform (GenAutoApply v) = genAutoApply platform v
genFile _        (GenJumps v)     = genJumps v

-- | The wrapper that instantiates rts/Jumps.h for one vector width, i.e.
-- the former rts/Jumps_{D,V16,V32,V64}.cmm.
genJumps :: Maybe Int -> String
genJumps mbVec = unlines $
  [ "// DO NOT EDIT!"
  , "// Automatically generated by GHC.StgToCmm.AutoApply (ghc --gen-apply=jumps" ++ suffix ++ ")"
  , ""
  , "#include \"Cmm.h\""
  , ""
  ] ++
  [ "#define ARG_REGS_V" ++ show w ++ " 1" | Just w <- [mbVec] ] ++
  [ "#include \"Jumps.h\"" ]
  where
    suffix = maybe "" (\w -> "-v" ++ show w) mbVec

