-- | Simple Setup.hs for ghc-boot
--
-- GHC.Version and GHC.Platform.Host modules are now generated by ./configure
-- from their .in templates (Version.hs.in, Platform/Host.hs.in).
-- The HADRIAN_SETTINGS environment variable mechanism has been removed.
module Main where

import Distribution.Simple

main :: IO ()
main = defaultMain
