/* -----------------------------------------------------------------------------
 *
 * (c) The University of Glasgow 2002-2004
 *
 * Declarations for the generic apply code.  It is generated by GHC
 * (GHC.StgToCmm.AutoApply) and linked into each program rather than into
 * the RTS, so these symbols are resolved at the program's final link; see
 * Note [Linking the generic apply code] in GHC.Driver.Pipeline.  They must
 * therefore have default visibility.
 *
 * -------------------------------------------------------------------------- */

#pragma once

// canned slow entry points, indexed by arg type (ARG_P, ARG_PP, etc.)
#if defined(IN_STG_CODE)
extern StgWord stg_ap_stack_entries[];
#else
extern StgFun *stg_ap_stack_entries[];
#endif

// canned register save code for heap check failure in a function
#if defined(IN_STG_CODE)
extern StgWord stg_stack_save_entries[];
#else
extern StgFun *stg_stack_save_entries[];
#endif
